---
# tasks file for vector-role
- name: Install Vector
  hosts: vector
  handlers:
    - name: Start vector
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted
  tasks:
    - name: Get vector distrib
      ansible.builtin.get_url:
        url: "https://apt.vector.dev/pool/v/ve/vector_{{ vector_version }}-1_amd64.deb"
        dest: "./vector_{{ vector_version }}-1_amd64.deb"
        mode: "0644"
    - name: Install vector distrib
      become: true
      ansible.builtin.apt:
        deb: "./vector_{{ vector_version }}-1_amd64.deb"
    - name: Deploy template config
      become: true
      ansible.builtin.template:
        src: "vector.yml.j2"
        dest: "{{ vector_config_dir }}/vector.yml"
        mode: "0644"
